name: BBedwars
version: '${version}'
main: tv.bytex.bbedwars.BBedwars
api-version: 1.19
commands:
  help:
    description: Zeigt die Hilfe an
  start:
    description: Startet ein Spiel
  stop:
    description: Stoppe ein Spiel
